#Data structure is about how data can be stored in different structures
#algorithms is about how to slove different problems often by searching through and manipulating data structures
#data structures are the way of storing and organizing data in a computer
#python has built in data structure like list,tuple,set,dicitionary
#other data structures can be implemented using classes and onjects such as linked lists,stacks,queues,trees,graphs,hash tables
#data structures
#list and arrays
#stacks
#queues
#linked lists
#hash tables
#trees
#binary trees
#binary search trees
#avl trees
#heaps
#graphs
#ALGORITHMS
#linear search
#binary search
#bubble sort
#selection sort
#insertion sort
#quick sort
#counting sort
#radix sort
#merge sort
#dijkstra's algorithm
#depth first search
#breadth first search
#dynamic programming
#greedy algortihms

